/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedKnowledgeBaseRouteImport } from './routes/_authenticated/knowledge-base'
import { Route as AuthenticatedMenuBotRouteImport } from './routes/_authenticated/menu-bot'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedStatistikRouteImport } from './routes/_authenticated/statistik'
import { Route as ApiWebhooksChateraRouteImport } from './routes/api/webhooks/chatera'
import { Route as ApiPublicWebhooksChateraRouteImport } from './routes/api/public/webhooks/chatera'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeBaseRoute =
  AuthenticatedKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuBotRoute = AuthenticatedMenuBotRouteImport.update({
  id: '/menu-bot',
  path: '/menu-bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatistikRoute = AuthenticatedStatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWebhooksChateraRoute = ApiWebhooksChateraRouteImport.update({
  id: '/api/webhooks/chatera',
  path: '/api/webhooks/chatera',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksChateraRoute =
  ApiPublicWebhooksChateraRouteImport.update({
    id: '/api/public/webhooks/chatera',
    path: '/api/public/webhooks/chatera',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/menu-bot': typeof AuthenticatedMenuBotRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/api/webhooks/chatera': typeof ApiWebhooksChateraRoute
  '/api/public/webhooks/chatera': typeof ApiPublicWebhooksChateraRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/menu-bot': typeof AuthenticatedMenuBotRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/webhooks/chatera': typeof ApiWebhooksChateraRoute
  '/api/public/webhooks/chatera': typeof ApiPublicWebhooksChateraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/_authenticated/menu-bot': typeof AuthenticatedMenuBotRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/statistik': typeof AuthenticatedStatistikRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/webhooks/chatera': typeof ApiWebhooksChateraRoute
  '/api/public/webhooks/chatera': typeof ApiPublicWebhooksChateraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/knowledge-base'
    | '/menu-bot'
    | '/pengaturan'
    | '/statistik'
    | '/api/webhooks/chatera'
    | '/api/public/webhooks/chatera'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/knowledge-base'
    | '/menu-bot'
    | '/pengaturan'
    | '/statistik'
    | '/'
    | '/api/webhooks/chatera'
    | '/api/public/webhooks/chatera'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/knowledge-base'
    | '/_authenticated/menu-bot'
    | '/_authenticated/pengaturan'
    | '/_authenticated/statistik'
    | '/_authenticated/'
    | '/api/webhooks/chatera'
    | '/api/public/webhooks/chatera'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiWebhooksChateraRoute: typeof ApiWebhooksChateraRoute
  ApiPublicWebhooksChateraRoute: typeof ApiPublicWebhooksChateraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-base': {
      id: '/_authenticated/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu-bot': {
      id: '/_authenticated/menu-bot'
      path: '/menu-bot'
      fullPath: '/menu-bot'
      preLoaderRoute: typeof AuthenticatedMenuBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistik': {
      id: '/_authenticated/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof AuthenticatedStatistikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhooks/chatera': {
      id: '/api/webhooks/chatera'
      path: '/api/webhooks/chatera'
      fullPath: '/api/webhooks/chatera'
      preLoaderRoute: typeof ApiWebhooksChateraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/chatera': {
      id: '/api/public/webhooks/chatera'
      path: '/api/public/webhooks/chatera'
      fullPath: '/api/public/webhooks/chatera'
      preLoaderRoute: typeof ApiPublicWebhooksChateraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKnowledgeBaseRoute: typeof AuthenticatedKnowledgeBaseRoute
  AuthenticatedMenuBotRoute: typeof AuthenticatedMenuBotRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedStatistikRoute: typeof AuthenticatedStatistikRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKnowledgeBaseRoute: AuthenticatedKnowledgeBaseRoute,
  AuthenticatedMenuBotRoute: AuthenticatedMenuBotRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedStatistikRoute: AuthenticatedStatistikRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiWebhooksChateraRoute: ApiWebhooksChateraRoute,
  ApiPublicWebhooksChateraRoute: ApiPublicWebhooksChateraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
